/**
 * The host API contract, in one place, for both consumers.
 *
 * `src/sandbox.ts` *provides* these globals to user code at runtime (see
 * `BOOTSTRAP` there). `src/typecheck.ts` *declares* them so `tsc` can see them.
 * The two must agree, or every program fails with TS2304 "Cannot find name".
 *
 * Keeping the compiler options here too means the type-checker's view of a
 * program is defined by one file rather than by a string literal buried in a
 * MemoryFs. The fixture generator in `scripts/gen-fixtures.mjs` reads this
 * same module, so the fixtures cannot drift from what the Worker enforces.
 *
 * These are plain data with no imports on purpose: node reads this file
 * directly via type stripping to generate the fixtures.
 */

/** Where the type-checker puts the program, inside its in-memory filesystem. */
export const APP_DIR = "/app";

/** The file name the user's source is written to, and the path diagnostics report. */
export const APP_ENTRY = `${APP_DIR}/index.ts`;

/**
 * Compiler options for the generated project.
 *
 * Every entry earns its place:
 *
 * - `strict` — the entire point. Sucrase stripped types without checking them.
 * - `noEmit` — we only want diagnostics. The QuickJS path runs the *sucrase*
 *   output, so letting tsc write .js files would be dead weight in the
 *   in-memory filesystem.
 * - `types: []` — the default is "every package under node_modules/@types".
 *   The in-memory filesystem has no `node_modules`, so that scan is pure
 *   error surface.
 * - `lib` — `esnext` for language built-ins, `dom` for `console`. Without
 *   `dom`, `console.log` is TS2584 "Cannot find name 'console'". The `dom` lib
 *   is a stand-in: QuickJS has no DOM, but the sandbox replaces `console`
 *   wholesale anyway, so nothing here can reach a real one.
 * - `skipLibCheck` — the bundled `lib.*.d.ts` come from TypeScript 7.1.0-dev.
 *   We check *user* code, not the compiler's own vendored declarations; an
 *   error inside them would otherwise block every program.
 * - `target`/`module` — `noEmit` makes these cosmetic, but without them tsc
 *   defaults to ES5/CommonJS and reports misleading downlevel errors.
 */
export const TSCONFIG = {
  compilerOptions: {
    strict: true,
    noEmit: true,
    types: [],
    lib: ["esnext", "dom"],
    skipLibCheck: true,
    target: "esnext",
    module: "esnext",
  },
} as const;

/**
 * Ambient declarations for the globals `BOOTSTRAP` installs.
 *
 * This file is generated into the type-checker's filesystem rather than kept on
 * disk, so a program can never `import` it and so it stays in lockstep with
 * `sandbox.ts`. If you add a global to `BOOTSTRAP`, add it here.
 *
 * `state` is `Record<string, any>` rather than `unknown` on purpose: the
 * idiomatic increment is `state.runs = (state.runs ?? 0) + 1`, and under
 * `unknown` every property read is an error, which would make the host API
 * unusable. The cost is that writes into `state` are unchecked — acceptable
 * for a mutable bag the host owns and user code is meant to reshape.
 */
export const GLOBALS_DTS = `// Generated by src/host-api.ts. Do not edit; edit GLOBALS_DTS instead.

declare const state: Record<string, any>;

/** Appends to the rendered output. The only output channel. */
declare function html(strings: TemplateStringsArray, ...values: unknown[]): void;
`;

/** Every file a type-check run needs, given the user's source. */
export function projectFiles(source: string): Record<string, string> {
  return {
    [`${APP_DIR}/tsconfig.json`]: JSON.stringify(TSCONFIG, null, 2),
    [`${APP_DIR}/globals.d.ts`]: GLOBALS_DTS,
    [APP_ENTRY]: source,
  };
}